### ISSUE TITLE
Accessing options inside link method

### ISSUE THREAD

**Issue by petrgazarov** [ruby-grape/grape-roar#17]
After bumping Roar from `1.0.1` to `1.0.4`, having issues with accessing options in `link` method block.

`representable` gem was also bumped from `2.1.8` to `3.0.0` by virtue of me upgrading `reform` from `1.2.6` to `2.1.0`.

No longer works:
```
class ClientsPresenter
  link :self do |options|
    options => nil ???
  end
end
```

With this calling `present` method:
```
resource :clients do
  get do
    present clients, with: ClientsPresenter
  end
end
```

I certainly do not have complete understanding of interplay between Roar ~ Representable ~ Grape libraries, but any thoughts/discussion would be really appreciated!

Thanks!

**Comment by dblock** [comment]
Something must have broke, I would start by upgrading it here and seeing if any of our existing specs fail?

**Comment by petrgazarov** [comment]
Daniel, thanks for the quick reply! So, when running specs:

**When using `representable < 2.4.0`:**
  - Life is great, all green.

**When using `representable 3.0.0`:**
  - `roar 1.0.3` or `1.0.1` gives me `uninitialized constant Representable::Inheritable`. I think Nick suggested a fix that solves it [here](https://github.com/apotonick/roar/issues/179). Anyway, here is the full trace:
```
$ bundle exec rspec
/Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/roar-1.0.3/lib/roar/hypermedia.rb:50:in `link_configs': uninitialized constant Representable::Inheritable (NameError)
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/roar-1.0.3/lib/roar/hypermedia.rb:128:in `link'
	from /Users/petrgazarov/workspace/grape-roar/spec/support/article_representer.rb:8:in `<module:ArticleRepresenter>'
	from /Users/petrgazarov/workspace/grape-roar/spec/support/article_representer.rb:1:in `<top (required)>'
	from /Users/petrgazarov/workspace/grape-roar/spec/support/article.rb:1:in `require'
	from /Users/petrgazarov/workspace/grape-roar/spec/support/article.rb:1:in `<top (required)>'
	from /Users/petrgazarov/workspace/grape-roar/spec/spec_helper.rb:21:in `require'
	from /Users/petrgazarov/workspace/grape-roar/spec/spec_helper.rb:21:in `block in <top (required)>'
	from /Users/petrgazarov/workspace/grape-roar/spec/spec_helper.rb:21:in `each'
	from /Users/petrgazarov/workspace/grape-roar/spec/spec_helper.rb:21:in `<top (required)>'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `block in requires='
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `each'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `requires='
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `each'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:105:in `setup'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/bin/rspec:23:in `load'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/bin/rspec:23:in `<main>'
```
  - When I pull from master, as suggested by Nick in the issue above, I end up with a different error, which seems to be coming from `declarative`: `undefined method 'link' for Article:Class`. Note that although I'm pulling from master, the roar version resolves to `1.0.3`. Full trace:
```
$ bundle exec rspec
/Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/declarative-0.0.7/lib/declarative/heritage.rb:18:in `call!': undefined method `link' for Article:Class (NoMethodError)
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/declarative-0.0.7/lib/declarative/heritage.rb:11:in `block in call'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/declarative-0.0.7/lib/declarative/heritage.rb:11:in `each'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/declarative-0.0.7/lib/declarative/heritage.rb:11:in `call'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/declarative-0.0.7/lib/declarative/heritage.rb:39:in `included'
	from /Users/petrgazarov/workspace/grape-roar/spec/support/article.rb:5:in `include'
	from /Users/petrgazarov/workspace/grape-roar/spec/support/article.rb:5:in `<class:Article>'
	from /Users/petrgazarov/workspace/grape-roar/spec/support/article.rb:3:in `<top (required)>'
	from /Users/petrgazarov/workspace/grape-roar/spec/spec_helper.rb:21:in `require'
	from /Users/petrgazarov/workspace/grape-roar/spec/spec_helper.rb:21:in `block in <top (required)>'
	from /Users/petrgazarov/workspace/grape-roar/spec/spec_helper.rb:21:in `each'
	from /Users/petrgazarov/workspace/grape-roar/spec/spec_helper.rb:21:in `<top (required)>'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `block in requires='
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `each'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `requires='
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `each'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:105:in `setup'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/bin/rspec:23:in `load'
	from /Users/petrgazarov/.rbenv/versions/2.2.2/bin/rspec:23:in `<main>'
```

My problem is that `reform 2.1.0` requires `representable >= 2.4.0` and this creates a bit of dependency challenge.

**Comment by dblock** [comment]
I am not sure what to do here other than wait till some things make progress and get released.

**Comment by apotonick** [comment]
This is not a `grape-roar` issue, @dblock! :beers: 

@petrgazarov Please use `roar/1-1` as your branch! It will require Representable 3.0.

**Comment by dblock** [comment]
Thanks @apotonick. I'll close this here.
